query getCommitSince($date: GitTimestamp!, $after: String = null) {
    repository(owner: "python-telegram-bot", name: "python-telegram-bot") {
        object(expression: "master") {
            ... on Commit {
                history(first: 100, since: $date, after: $after) {
                    nodes {
                        messageHeadline
                        messageBody
                    }
                    pageInfo {
                        hasNextPage
                        endCursor
                        __typename
                    }
                }
            }
        }
    }
}